# version: '3.8' ??

networks:
  Inception:
    name: Inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${HOME}/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${HOME}/data/mariadb"

services:
  mariadb:
    networks:
      - Inception
    volumes:
      - mariadb:/var/lib/mysql
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping"] #?
    #   interval: 5s
    #   timeout: 2s
    #   retries: 2
    env_file:
      - .env
    restart: on-failure
  
  wordpress:
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_healthy
        
    networks:
      - Inception
    volumes:
      - wordpress:/home
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure

  nginx:
    depends_on:
      - wordpress #?
    networks:
      - Inception
    volumes:
      - wordpress:/home
    image: nginx
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
  

  
